name: Update versions in Readme



# This is an event listener this action will only run on Push to main branch

on: 
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update versions in Readme
        id: versions
        run: |
         NEXT_VERSION=$(jq -r '.version' web/package.json)
          echo "next=$NEXT_VERSION" >> $GITHUB_OUTPUT
         NEST_VERSION=$(jq -r '.version' backend/package.json)
          echo "nest=$NEST_VERSION" >> $GITHUB_OUTPUT
         
         IOS_VERSION="NA"
         PBXPROH=$(find . -name "project.pbxproj" | head -n 1)
         if [-n "$PBXPROJ"]; then
            IOS_VERSION=$(grep -m 1 "MARKETING_VERSION" "$PBXPROJ" | sed 's/.*= \(.*\); /\1/') | tr -d ' '
            fi

      - name: Update Readme
        run: |
         sed -i "s|<!--NEXT_VERSION-->.*<!--NEXT_VERSION_END-->|<!--NEXT_VERSION-->${{steps.versions.outputs.next}}  <!--NEXT_VERSION_END-->|" README.md


      - name: Commit and Push changes
        run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git add README.md
          git commit -m  "chore:Update versions in Readme" || echo "No changes to commit"
          git push
